# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
executors:
  node_image:
    docker:
      - image: circleci/node:10.18.0-browsers
    working_directory: /tmp/projects/web
jobs:
  install:
    executor: node_image
    steps:
      - checkout
      # - run:
      #     name: "change working dir"
      #     command: "cd projects/web"
      # - run:
      #     name: "list files"
      #     command: "ls -la"
      # - run:
      #     name: "print working dir"
      #     command: "pwd"
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "projects/web/package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install projects/web
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "projects/web/package-lock.json" }}
      - persist_to_workspace:
          root: ./projects/web
          paths:
            - node_modules
      - run:
          name: "list files"
          command: "ls projects/web -la"
  # build:
  #   executor: node_image
  #   steps:
  #     - checkout
  #     - attach_workspace:
  #         at: /tmp/we-the-party
  #     - run: npm run build --production
  #     - persist_to_workspace:
  #         root: ./
  #         paths:
  #           - dist
  # test:
  #   executor: node_image
  #   steps:
  #     - checkout
  #     - attach_workspace:
  #         at: /tmp/we-the-party
  #     - run: npm run test
  # deploy:
  #   executor: node_image
  #   steps:
  #     - checkout
  #     - attach_workspace:
  #         at: /tmp/we-the-party
  #     - run: sudo apt-get update && sudo apt-get install python3-pip
  #     - run: sudo pip3 install awscli
  #     # `deploy` step: identical to a `run` step, but uses only one container:
  #     # /docs/2.0/configuration-reference/#deploy
  #     - deploy:
  #         name: deploy to AWS
  #         command: |
  #           if [ "${CIRCLE_BRANCH}" = "master" ]; then
  #             aws s3 sync ./dist/we-the-party \
  #             s3://wethe.party --delete
  #           else
  #             aws s3 sync ./dist/we-the-party \
  #             s3://dev.wethe.party --delete
  #           fi
workflows:
  ci_cd_harness:
    jobs:
      - install
      # - build:
      #     context: WTP_ENV_DEV
      #     name: build_dev
      #     filters:
      #       branches:
      #         ignore:
      #           - master
      #     requires:
      #       - install
      # - build:
      #     context: WTP_ENV_PROD
      #     name: build_prod
      #     filters:
      #       branches:
      #         only:
      #           - master
      #     requires:
      #       - install
      # - test:
      #     context: WTP_ENV_DEV
      #     requires:
      #       - install
      # - deploy:
      #     name: deploy_prod
      #     requires:
      #       - build_prod
      #       - test
      #     filters:
      #       branches:
      #         only:
      #           - master
      # - deploy:
      #     name: deploy_dev
      #     requires:
      #       - build_dev
      #       - test
      #     filters:
      #       branches:
      #         only:
      #           - develop
