# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
executors:
  web_builder_image:
    docker:
      - image: circleci/node:14.15.4-browsers
    working_directory: /tmp/wtp-platform
jobs:
  install:
    executor: web_builder_image
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "projects/web/package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: cd projects/web && npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "projects/web/package-lock.json" }}
      - persist_to_workspace:
          root: projects/web
          paths:
            - node_modules

  build:
    executor: web_builder_image
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/wtp-platform/projects/web
      - run: cd projects/web && npm run build
      - run:
          name: "list contents"
          command: "cd projects/web && ls -la"
      - persist_to_workspace:
          root: projects/web
          paths:
            - build
  test:
    executor: web_builder_image
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/wtp-platform/projects/web
      - run: cd projects/web && npm run test
      - run:
          name: "list contents"
          command: "cd projects/web && ls -la"
  deploy:
    executor: web_builder_image
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/wtp-platform/projects/web
      - run:
          name: "list contents"
          command: "cd projects/web && ls -la"
      - run: sudo apt-get update && sudo apt-get install python3-pip
      - run: sudo pip3 install awscli
      - run:
          name: "list files"
          command: "ls -la projects/web"
      # `deploy` step: identical to a `run` step, but uses only one container:
      # /docs/2.0/configuration-reference/#deploy
      - deploy:
          name: deploy to AWS
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              aws s3 sync ./projects/web/build \
              s3://wethe.party --delete
            else
              aws s3 sync ./projects/web/build \
              s3://dev.wethe.party --delete
            fi
workflows:
  ci_cd_harness:
    jobs:
      - install
      - build:
          context: WTP_ENV_DEV
          name: build_dev
          filters:
            branches:
              ignore:
                - master
          requires:
            - install
      - build:
          context: WTP_ENV_PROD
          name: build_prod
          filters:
            branches:
              only:
                - master
          requires:
            - install
      - test:
          context: WTP_ENV_DEV
          requires:
            - install
      - deploy:
          context: aws-credentials
          name: deploy_prod
          requires:
            - build_prod
            - test
          filters:
            branches:
              only:
                - master
      - deploy:
          context: aws-credentials
          name: deploy_dev
          requires:
            - build_dev
            - test
          filters:
            branches:
              only:
                - develop
